okta:
  oauth2:
    issuer: https://dev-94528537.okta.com/oauth2/default
    client-secret: XtbkpAMYTMz7B22x7heNwDiR1g9J49iJzW9FIpGy
    client-id: 0oa3fliep9eL6NQbL5d7
    scopes: openid, profile, email
    redirect-uri: /authorization-code/callback

logging:
   pattern:
     console: "%msg%n"
   level:
     root: debug
     org:
       springframework:
         security: debug